# Generated by Django 5.0.6 on 2025-02-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('goal', models.CharField(choices=[('Athletic Body', 'Athletic Body'), ('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Healthy Body', 'Healthy Body')], max_length=20)),
                ('target_weight', models.FloatField(blank=True, null=True)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
