# Generated by Django 5.0.6 on 2025-02-28 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionApp', '0002_suggestionmeal_alter_profile_username_usermealplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='meal_images/')),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('fats', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usermealplan',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='usermealplan',
            name='user',
        ),
        migrations.CreateModel(
            name='UserMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutritionApp.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SuggestionMeal',
        ),
        migrations.DeleteModel(
            name='UserMealPlan',
        ),
    ]
